spring:
  application:
    name: MS-Students

  jpa:
    hibernate:
      ddl-auto: none

  datasource:
    url: jdbc:mysql${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:some_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    driverClassName: org.mariadb.jdbc.Driver

  flyway:
    url: jdbc:mysql${MYSQL_HOST:localhost}:3306/${MYSQL_DATABASE:some_db}
    schemas: ${MYSQL_DATABASE:some_db}
    username: ${MYSQL_USER:root}
    password: ${MYSQL_PASSWORD:root}
    locations: classpath:db/migration
    enabled: true

  redis:
    database: ${REDIS_DATABASE:3}
    host: ${REDIS_HOST:localhost}
    port: 6379

  cache:
    type: redis
    redis:
      cache-null-values: false
      time-to-live: 600000
